export const qualkeyUploadMapping = new Map([
   ["email", "Email"],
   ["authenticatedBy", "Authenticated by"],
   ["authenticatedDate", "Authenticated Date"],
   ["authenticatedTitle", "Authenticated Title"],
   ["awardLevel", "Award Level"],
   ["awardingInstitution", "Awarding Institution"],
   ["expiresAt", "Expires At"],
   ["graduatedAt", "Graduated At"],
   ["graduatedFullName", "Graduated Full Name"],
   ["graduatedFirstName", "Graduated First Name"],
   ["graduatedLastName", "Graduated Last Name"],
   ["graduatedMiddleName", "Graduated Middle Name"],
   ["info", "Info"],
   ["minors", "Minors"],
   ["majors", "Majors"],
   ["gpaFinalGrade", "GPA Final Grade"],
   ["qualificationLevel", "Qualification Level"],
   ["qualificationName", "Qualification Name"],
   ["studyEndedAt", "Study Ended At"],
   ["studyLanguage", "Study Language"],
   ["studyStartedAt", "Study Started At"],
])